services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: devops-lab-service
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - app
